version: '3.7'
volumes:
  pgdata:
services:
  web:
    build:
      context: .
    volumes:
      - .:/myapp
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"