version: '3.7'
services:
  web:
    build:
      context: .
    volumes:
      - .:/myapp
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:3000"

  frontend:
    image: node:14
    working_dir: /myapp/frontend
    command: script/build
    volumes:
      - .:/myapp

  postgres:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"