version: '3.7'
services:
  web:
    build:
      context: ./web/
    volumes:
      - ./web/:/myapp
    depends_on:
      postgres: {condition: service_healthy}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "3001:3001"

  postgres:
    image: postgres:14
    volumes:
      - ./web/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"