version: '3.7'
services:
  web:
    build:
      context: ./web/
    volumes:
      - ./web/:/myapp
    depends_on:
      postgres: {condition: service_healthy}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:3000"

  # This is odd - but all I do is build the frontend with this step
  # It won't hot reload
  frontend:
    image: node:14
    working_dir: /myapp/frontend
    command: script/build
    volumes:
      - .:/myapp

  postgres:
    image: postgres:14
    volumes:
      - ./web/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"