---
name: Deploy
on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
  deploy:
    name: deploy
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow succeeded deploying now'
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: "38b58b68-a4d4-4422-b195-e5884fe05638"
          heroku_app_name: "agile-chamber-34431" #Must be unique in Heroku
          heroku_email: "lizjohnson@thisisartium.com"
          usedocker: true